name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    container: python:3.8  # Optionally, specify a Docker container image with Python installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Django
        run: pip install Django==3.2

      - name: Trivy FS Scan
        run: |
          trivy fs --format table -o trivy-fs-report.html .

      - name: Build Docker Image
        run: |
          docker build -t kiranprav/python:latest .

      - name: Trivy Image Scan
        run: |
          trivy image --format table -o trivy-image-report.html kiranprav:latest
