name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: test

    steps:
      - name: Build with Maven
        run: mpip install Django==3.2

      - name: Trivy FS Scan
        run: |
          trivy fs --format table -o trivy-fs-report.html .

      - name: Build Docker Image
        run: |
          docker build -t kiranprav/python:latest .

      - name: Trivy Image Scan
        run: |
          trivy image --format table -o trivy-image-report.html kiranprav:latest

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Push Docker Image
#        run: |
#            docker push kiranprav/kiranabhishek:latest
